TUTORS_FILE_PATH = "database/tutors.json"
LEARNERS_FILE_PATH = "database/learners.json"
ADMIN_FILE_PATH = "database/admin.json"
TEACHERS_FILE_PATH = "database/teachers.json"
LESSONS_FILE_PATH = "database/lessons.json"
COURSES_FILE_PATH = "database/courses.json"
QUIZZES_FILE_PATH = "database/quiz.json"
GRADES_FILE_PATH = "database/grades.json"
ASSIGNMENTS_FILE_PATH = "database/assignments.json"
SUBMISSIONS_FILE_PATH = "database/submissions.json"
FORUM_FILE_PATH = "database/forum.json"

LOGO_PATH = "Picture/EmpowerU Logo.png"
FONT_FAMILY = "Roboto"
